let regexp = /<(([a-z]+)(\s+([^>]*))*)>/;
let str = '<div id="top">';
let result = str.match(regexp);
console.log(`Complete tag: ${result[0]}`);
console.log(`Tag cotent: ${result[1]}`);
console.log(`Tag name: ${result[2]}`);
console.log(`Attribute: ${result[3]}`);
str = '<div id="top" class="normal">';
result = str.match(regexp);
console.log(`Complete tag: ${result[0]}`);
console.log(`Tag cotent: ${result[1]}`);
console.log(`Tag name: ${result[2]}`);
console.log(`Attribute: ${result[3]}`);
str = '<div>';
result = str.match(regexp);
console.log(`Complete tag: ${result[0]}`);
console.log(`Tag cotent: ${result[1]}`);
console.log(`Tag name: ${result[2]}`);
console.log(`Attribute: ${result[3]}`);
